CC = gcc
CFLAGS = -Wall -g
LIBS = -lsqlite3
SRC = src/main.c src/database.c src/menu.c src/student.c
OBJ = $(SRC:.c=.o)
EXEC = grade_management_system

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(EXEC) $(LIBS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(EXEC)

.PHONY: all clean